import type { CSSProperties } from "react";
import { font, H, W } from "./theme";

/**
 * 横版 `B50Poster` 壳层与左栏 / 右栏头（不含曲卡、背景、通用 Panel 内部）。
 */
export const posterStyles = {
  root: {
    position: "relative",
    display: "flex",
    width: W,
    height: H,
    overflow: "hidden",
    backgroundColor: "#f7f4ff",
    color: "#23194d",
    fontFamily: font,
  },
  leftPane: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    width: 650,
    padding: "22px 28px 0 30px",
  },
  rightPane: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    width: 1270,
    padding: "0 28px 0 0",
  },
  /** 左上玩家区：固定高度留给下方 TOP5，内部用间距透气而非硬塞 */
  playerBlock: {
    display: "flex",
    flexDirection: "column",
    height: 292,
    paddingTop: 22,
  },
  sectionLabel: {
    display: "flex",
    fontSize: 13,
    color: "#7c62d5",
    fontWeight: 700,
    letterSpacing: 1.5,
  },
  nameRow: {
    display: "flex",
    alignItems: "center",
    marginTop: 10,
    minHeight: 48,
  },
  playerName: {
    display: "flex",
    fontSize: 40,
    lineHeight: 1.05,
    fontWeight: 700,
    marginRight: 4,
  },
  nameRankBadge: {
    display: "flex",
    marginLeft: 12,
    height: 44,
    objectFit: "contain",
    flexShrink: 0,
  },
  profileRow: {
    display: "flex",
    alignItems: "center",
    marginTop: 18,
    width: "100%",
  },
  avatarRing: {
    display: "flex",
    width: 118,
    height: 118,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    flexShrink: 0,
  },
  avatar: { borderRadius: 999, objectFit: "cover" },
  ratingBox: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    marginLeft: 20,
    width: 148,
    height: 100,
    paddingLeft: 18,
    borderLeft: "2px solid #b79eee",
    flexShrink: 0,
  },
  mutedLabel: {
    display: "flex",
    fontSize: 12,
    color: "#5f4aa6",
    fontWeight: 700,
    letterSpacing: 1.2,
    marginBottom: 4,
  },
  bigRating: {
    display: "flex",
    fontSize: 44,
    lineHeight: 1,
    color: "#6939c7",
    fontWeight: 800,
  },
  /** 吃满左栏剩余宽度，减少 B15 左侧空白感 */
  scoreBox: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 180,
    height: 108,
    marginLeft: 16,
    marginRight: 4,
    padding: "10px 18px",
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,.62)",
    boxShadow: "0 8px 22px rgba(113, 82, 190, .12)",
  },
  generated: {
    display: "flex",
    marginTop: 14,
    fontSize: 12,
    color: "#5a4a88",
    fontWeight: 600,
  },
  panelTitleSmall: { display: "flex", fontSize: 15, color: "#5b3fb5", fontWeight: 800 },
  topCards: { display: "flex", gap: 9, marginTop: 34 },
  statsRow: { display: "flex", height: "100%" },
  statCell: {
    display: "flex",
    flexDirection: "column",
    width: 288,
    borderRight: "1px solid #c7b7ef",
  },
  statCellRight: { display: "flex", flexDirection: "column", width: 301, paddingLeft: 16 },
  donutRow: { display: "flex", alignItems: "center", marginTop: 16 },
  legend: { display: "flex", flexDirection: "column", gap: 5, marginLeft: 18 },
  legendRow: { display: "flex", alignItems: "center", fontSize: 10.5, fontWeight: 700 },
  legendDot: { display: "flex", width: 9, height: 9, borderRadius: 2, marginRight: 6 },
  legendLabel: { display: "flex", width: 56, whiteSpace: "nowrap" },
  legendValue: { display: "flex", width: 20 },
  legendPercent: { display: "flex", width: 44, color: "#594a8f", whiteSpace: "nowrap" },
  bottomStats: { display: "flex", height: "100%" },
  radarArea: {
    display: "flex",
    flexDirection: "column",
    width: 285,
    borderRight: "1px solid #c7b7ef",
  },
  personalArea: {
    display: "flex",
    flexDirection: "column",
    width: 304,
    paddingLeft: 16,
    paddingRight: 8,
  },
  metricsGrid: {
    display: "flex",
    flexWrap: "wrap",
    width: 276,
    marginTop: 12,
    alignContent: "space-between",
    height: 188,
  },
  /** 画布底部页脚条（左右文案） */
  footerBar: {
    position: "absolute",
    left: 28,
    right: 28,
    bottom: 8,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: 22,
  },
  footerLeft: {
    display: "flex",
    fontSize: 14,
    color: "#7e5ede",
    fontWeight: 700,
  },
  footerRight: {
    display: "flex",
    fontSize: 14,
    color: "#7e5ede",
    fontWeight: 700,
  },
  boardHeader: {
    position: "absolute",
    left: 10,
    right: 0,
    top: 18,
    display: "flex",
    height: 42,
    alignItems: "center",
  },
  b50Title: { display: "flex", alignItems: "baseline", marginLeft: 10 },
  b50Strong: { fontSize: 31, fontWeight: 800, marginRight: 11, color: "#7b4ce1" },
  b50Text: { fontSize: 20, fontWeight: 800, color: "#7b4ce1" },
} satisfies Record<string, CSSProperties>;
