import type { CSSProperties } from "react";
import {
  LANDSCAPE_CARD_COVER,
  LANDSCAPE_CARD_HEIGHT,
  songCardWidth,
  songGridGap,
  songGridWidth,
  songSectionWidth,
} from "./theme";

const infoWidth = songCardWidth - LANDSCAPE_CARD_COVER - 11;
const titleWidth = songCardWidth - LANDSCAPE_CARD_COVER - 21;

/**
 * TOP 5（`TopCard`）+ B50 曲卡（`SongCard` / `SongSection`）。
 * B15 / B35 共用同一卡高与方形封面。
 */
export const songCardStyles = {
  // ── TOP 5 ──────────────────────────────────────────────────────────────
  topCards: { display: "flex", gap: 9, marginTop: 34 },
  topCard: {
    position: "relative",
    display: "flex",
    width: 111,
    height: 220,
    overflow: "hidden",
    borderRadius: 6,
    backgroundColor: "#24194f",
  },
  topCover: { position: "absolute", inset: 0, objectFit: "cover" },
  topShade: {
    display: "flex",
    position: "absolute",
    inset: 0,
    backgroundImage:
      "linear-gradient(180deg, rgba(20,13,47,0) 30%, rgba(20,13,47,.78) 55%, rgba(20,13,47,.95) 100%)",
  },
  topIndex: {
    display: "flex",
    position: "absolute",
    left: 0,
    top: 0,
    padding: "2px 7px",
    backgroundColor: "#9b63f1",
    color: "#fff",
    fontSize: 22,
    fontWeight: 800,
  },
  topMeta: {
    position: "absolute",
    left: 6,
    right: 6,
    bottom: 7,
    display: "flex",
    flexDirection: "column",
    color: "#fff",
    textShadow: "0 1px 4px rgba(0,0,0,.95), 0 0 6px rgba(0,0,0,.75)",
  },
  songTitle: {
    display: "flex",
    width: 104,
    fontSize: 13,
    fontWeight: 700,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  ach: { display: "flex", fontSize: 16, fontWeight: 800, marginTop: 4 },
  dxLargeRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    marginTop: 3,
  },
  dxLarge: {
    display: "flex",
    fontSize: 13,
    lineHeight: 1.1,
    fontWeight: 800,
    color: "#ffffff",
    whiteSpace: "nowrap",
    textShadow: "0 1px 2px rgba(0,0,0,1), 0 0 6px rgba(0,0,0,.95), 0 0 1px #000",
  },
  dxStars: { display: "flex", flexDirection: "row", alignItems: "center", gap: 0, flexShrink: 0 },
  dxStar: { display: "flex", width: 10, height: 10, objectFit: "contain" },
  masterRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: 12,
    fontWeight: 700,
  },
  masterPill: { backgroundColor: "#7444d7", color: "#fff", padding: "1px 5px", borderRadius: 2 },

  // ── B15 / B35 统一曲卡 ─────────────────────────────────────────────────
  songSection: {
    position: "absolute",
    left: 20,
    width: songSectionWidth,
    display: "flex",
    flexDirection: "column",
    padding: "10px 10px 12px 10px",
    border: "2px solid #b49ced",
    borderRadius: 9,
    backgroundColor: "rgba(255,255,255,.32)",
  },
  songSectionTitle: { display: "flex", alignItems: "center", height: 30, marginLeft: 10 },
  songSectionMain: { fontSize: 25, fontWeight: 800, color: "#7b4ce1", marginRight: 8 },
  songSectionSub: { fontSize: 18, fontWeight: 700, marginRight: 18 },
  songRule: { display: "flex", height: 2, width: 180, backgroundColor: "#b39aeb" },
  songGrid: {
    display: "flex",
    flexWrap: "wrap",
    width: songGridWidth,
    rowGap: songGridGap,
    columnGap: songGridGap,
    padding: "2px 0 0 0",
  },
  songCard: {
    position: "relative",
    display: "flex",
    width: songCardWidth,
    height: LANDSCAPE_CARD_HEIGHT,
    overflow: "hidden",
    borderRadius: 5,
    backgroundColor: "#24194f",
    color: "#fff",
    boxShadow: "0 2px 0 rgba(255,255,255,.45)",
  },
  coverStack: {
    position: "relative",
    display: "flex",
    width: LANDSCAPE_CARD_COVER,
    height: LANDSCAPE_CARD_COVER,
    flexShrink: 0,
  },
  songCover: {
    width: LANDSCAPE_CARD_COVER,
    height: LANDSCAPE_CARD_COVER,
    objectFit: "cover",
  },
  coverIndex: {
    display: "flex",
    position: "absolute",
    left: 0,
    bottom: 0,
    padding: "1px 4px",
    backgroundColor: "rgba(20,13,47,.85)",
    color: "#fff",
    fontSize: 11,
    fontWeight: 800,
    lineHeight: 1.2,
  },
  songInfo: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    width: infoWidth,
    height: LANDSCAPE_CARD_HEIGHT,
    padding: "4px 6px 4px 8px",
  },
  cardTitle: {
    display: "flex",
    width: titleWidth,
    fontSize: 13,
    fontWeight: 800,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  cardAchRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    width: titleWidth,
    marginTop: 3,
  },
  cardAch: {
    display: "flex",
    fontSize: 15,
    fontWeight: 800,
    lineHeight: 1,
    marginRight: 4,
  },
  cardDxRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    marginTop: 2,
  },
  cardDx: {
    display: "flex",
    fontSize: 11,
    lineHeight: 1,
    color: "#dfc7ff",
    fontWeight: 800,
    whiteSpace: "nowrap",
  },
  cardDxStar: { display: "flex", width: 8, height: 8, objectFit: "contain" },
  cardBottom: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: titleWidth,
    marginTop: 2,
  },
  cardBottomLeft: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 1,
  },
  cardRating: { fontSize: 13, lineHeight: 1, color: "#ffb44d", fontWeight: 800 },
  cardRateImage: {
    display: "flex",
    width: 36,
    height: 17,
    objectFit: "contain",
    marginLeft: 2,
  },
  cardLevel: { fontSize: 10, lineHeight: 1, color: "#ffa7bb", fontWeight: 800, marginRight: 6 },
  cardChartRating: {
    fontSize: 11,
    lineHeight: 1,
    color: "#ffd56a",
    fontWeight: 800,
  },
  cardBadgeImage: { display: "flex", width: 15, height: 15, objectFit: "contain", flexShrink: 0 },
} satisfies Record<string, CSSProperties>;
